pipeline {
    agent { 
        label 'linux-node' 
     }

    
    tools {
        terraform 'terraform1.13'
    }

    stages {
        stage('version') {
            steps {
               sh 'terraform version'
            }
        }
        
        stage('terra') {
            steps {
                dir('J-TERRA-main/T-Scripts') {
                    sh "terraform init"    
                    sh "terraform plan"
                    //sh "terraform apply --var-file terraform.tfvars --auto-approve"
                    sh "terraform destroy --auto-approve"
                }
                
            }
        }
    }
}
